version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NOAA
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  noaa-data-loader:
    build:
      context: ./NOAA-data-loader
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: